# Generated by Django 4.0.4 on 2022-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='private_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
