# Generated by Django 4.0.4 on 2022-04-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_app', '0004_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
