# Generated by Django 4.0.4 on 2022-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_app', '0005_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=100)),
                ('page_number', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=50000)),
            ],
        ),
    ]
