# Generated by Django 4.0.4 on 2022-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_app', '0008_blogs_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100)),
            ],
        ),
    ]
